name: luckyfruit
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
# flutter_v1.9.1+hotfix.6
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 用于本地存储;如不满足需求可用path_provider
  shared_preferences: ^0.5.6+2
  # 吐司
  oktoast: 2.3.1+1
  # AES加密
  encrypt: ^3.3.1
  # 界面适配
  flutter_screenutil: ^1.0.2
  # 网络请求
  dio: ^3.0.9
  # 数据管理
  provider: ^4.0.4
  #国际化和本地化功能，包括消息翻译，复数形式和性别，日期/数字格式和解析以及双向文本。
  intl: ^0.16.0
  # 在移动平台中启动URL
  # url_launcher: ^5.4,2
  # Loading动画 随时间变化而变化的加载指示器集合
  flutter_spinkit: ^4.1.2
  # 获取设备信息
  device_info: ^0.4.1+5
  # Server-Sent Events
  eventsource: ^0.2.2
  #用于查询有关应用程序包的信息
  package_info: ^0.4.0+16
  # 可同时播放多个音频文件
  audioplayers: ^0.14.2
  #  lottie动画
  lottie: ^0.3.2
  # To select multiple values Using Selector<> without having to
  # write a class that implements ==, the easiest solution is to use a "Tuple"
  tuple: ^1.0.3
  # wraps an existing Flutter widget 
  # and fires a callback when the widget's visibility changes
  visibility_detector: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/
    - assets/bgm/
    - assets/lottiefiles/
    - assets/city/
    - assets/tree/
    - assets/city/hawaii/
    - assets/image/
    - assets/image/2.0x/
    - assets/image/3.0x/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: black
      fonts:
        - asset: assets/font/BLACK.OTF
    - family: bold
      fonts:
        - asset: assets/font/BOLD.OTF
    - family: semibold
      fonts:
        - asset: assets/font/SEMIBOLD.OTF
    - family: regular
      fonts:
        - asset: assets/font/Regular.ttf
    # - family: CN-Bold
    #   fonts:
    #     - asset: assets/font/CN-Bold.otf
    # - family: CN-Heavy
    #   fonts:
    #     - asset: assets/font/CN-Heavy.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
